// Shared species/breed/color reference data for every "Register/Add Pet"
// form in the app (Animal Patients, and the Create Appointment "Add Pet"
// modal) -- kept in one place so both forms offer the exact same options
// and never drift apart.

export const SPECIES_GROUPS = [
  {
    label: "Common Household Pets",
    options: [
      "Dog",
      "Cat",
      "Rabbit",
      "Guinea Pig",
      "Hamster",
      "Mouse",
      "Rat",
      "Gerbil",
      "Ferret",
      "Chinchilla",
      "Hedgehog",
      "Sugar Glider",
    ],
  },
  {
    label: "Birds",
    options: [
      "Parrot",
      "Cockatiel",
      "Budgerigar",
      "Lovebird",
      "Canary",
      "Finch",
      "Pigeon",
      "Dove",
      "Chicken",
      "Duck",
      "Goose",
      "Turkey",
      "Quail",
    ],
  },
  {
    label: "Fish",
    options: [
      "Goldfish",
      "Betta Fish",
      "Koi",
      "Guppy",
      "Molly",
      "Platy",
      "Swordtail",
      "Tetra",
      "Cichlid",
      "Angelfish",
      "Catfish",
    ],
  },
  {
    label: "Reptiles",
    options: [
      "Turtle",
      "Tortoise",
      "Gecko",
      "Iguana",
      "Chameleon",
      "Bearded Dragon",
      "Snake",
    ],
  },
  {
    label: "Amphibians",
    options: [
      "Frog",
      "Toad",
      "Salamander",
      "Newt",
      "Axolotl",
    ],
  },
  {
    label: "Farm and Companion Animals",
    options: [
      "Goat",
      "Sheep",
      "Pig",
      "Horse",
      "Pony",
      "Donkey",
      "Cow",
      "Carabao",
      "Llama",
      "Alpaca",
    ],
  },
  {
    label: "Other",
    options: ["Other"],
  },
];

export const SPECIES_OPTIONS = SPECIES_GROUPS.flatMap(
  (group) => group.options
);

export const SEX_OPTIONS = [
  "Unknown",
  "Male",
  "Female",
];

export const BREEDS_BY_SPECIES = {
  Dog: [
    "Aspin (Askal)",
    "Labrador Retriever",
    "Golden Retriever",
    "German Shepherd",
    "Poodle",
    "Shih Tzu",
    "Chihuahua",
    "Beagle",
    "Siberian Husky",
    "Pomeranian",
    "Rottweiler",
    "Dachshund",
    "Bulldog",
    "French Bulldog",
    "Shiba Inu",
    "Corgi",
    "Doberman Pinscher",
    "Great Dane",
    "Border Collie",
    "Japanese Spitz",
    "Mixed Breed",
  ],
  Cat: [
    "Puspin (Domestic Shorthair)",
    "Persian",
    "Siamese",
    "Maine Coon",
    "British Shorthair",
    "Ragdoll",
    "Bengal",
    "Scottish Fold",
    "American Shorthair",
    "Sphynx",
    "Himalayan",
    "Mixed Breed",
  ],
  Rabbit: [
    "Holland Lop",
    "Netherland Dwarf",
    "Rex",
    "Angora",
    "Lionhead",
    "Dutch",
    "Flemish Giant",
    "Mixed Breed",
  ],
  "Guinea Pig": [
    "American",
    "Abyssinian",
    "Peruvian",
    "Silkie",
    "Teddy",
    "Texel",
  ],
  Hamster: [
    "Syrian",
    "Dwarf Campbell Russian",
    "Winter White",
    "Roborovski",
    "Chinese",
  ],
  Horse: [
    "Philippine Native Pony",
    "Arabian",
    "Thoroughbred",
    "Quarter Horse",
    "Appaloosa",
  ],
  Pony: [
    "Philippine Native Pony",
    "Shetland Pony",
    "Welsh Pony",
  ],
  Goat: [
    "Native / Native Cross",
    "Boer",
    "Anglo-Nubian",
    "Saanen",
  ],
  Cow: [
    "Native",
    "Holstein",
    "Brahman",
    "Sahiwal",
  ],
  Carabao: [
    "Native Carabao",
    "Murrah Buffalo",
  ],
  Pig: [
    "Native",
    "Landrace",
    "Large White",
    "Duroc",
  ],
  Chicken: [
    "Native (Darag)",
    "Rhode Island Red",
    "Leghorn",
    "Broiler",
  ],
  Duck: [
    "Native (Itik)",
    "Pekin",
    "Muscovy",
    "Khaki Campbell",
  ],
};

// Common colors/markings per species -- "Other" is appended separately in
// the dropdown (same convention as BREEDS_BY_SPECIES) so a color outside
// this list can still be typed in. Species not listed here keep the plain
// free-text color field, exactly like a species with no BREEDS_BY_SPECIES
// entry keeps a free-text breed field.
export const COLORS_BY_SPECIES = {
  Dog: [
    "Black",
    "White",
    "Brown",
    "Golden",
    "Cream",
    "Gray",
    "Fawn",
    "Red",
    "Brindle",
    "Black and White",
    "Brown and White",
    "Tricolor",
    "Merle",
    "Spotted",
    "Mixed / Multi-color",
  ],
  Cat: [
    "Black",
    "White",
    "Orange / Ginger",
    "Gray",
    "Brown",
    "Cream",
    "Calico",
    "Tabby",
    "Tortoiseshell",
    "Bicolor",
    "Tuxedo (Black and White)",
    "Siamese Point",
    "Mixed / Multi-color",
  ],
  Rabbit: [
    "White",
    "Black",
    "Brown",
    "Gray",
    "Fawn",
    "Chestnut",
    "Broken (Spotted)",
    "Tricolor",
    "Mixed / Multi-color",
  ],
  "Guinea Pig": [
    "White",
    "Black",
    "Brown",
    "Cream",
    "Tan",
    "Tortoiseshell",
    "Brindle",
    "Mixed / Multi-color",
  ],
  Hamster: [
    "Golden",
    "White",
    "Gray",
    "Black",
    "Brown",
    "Cream",
    "Banded",
    "Mixed / Multi-color",
  ],
  Horse: [
    "Bay",
    "Black",
    "Chestnut",
    "Gray",
    "Palomino",
    "Brown",
    "White",
    "Roan",
    "Pinto / Spotted",
  ],
  Pony: [
    "Bay",
    "Black",
    "Chestnut",
    "Gray",
    "Palomino",
    "Brown",
    "White",
    "Pinto / Spotted",
  ],
  Goat: [
    "White",
    "Black",
    "Brown",
    "Gray",
    "Spotted",
    "Mixed / Multi-color",
  ],
  Cow: [
    "Black",
    "White",
    "Brown",
    "Black and White",
    "Brown and White",
    "Red",
  ],
  Carabao: [
    "Gray",
    "Black",
    "White (Albino)",
  ],
  Pig: [
    "Pink",
    "White",
    "Black",
    "Black and White",
    "Brown",
  ],
  Chicken: [
    "White",
    "Black",
    "Brown",
    "Red",
    "Black and White",
    "Speckled",
    "Mixed / Multi-color",
  ],
  Duck: [
    "White",
    "Black",
    "Brown",
    "Gray",
    "Mixed / Multi-color",
  ],
};
