import React, { useEffect, useMemo, useState } from "react";
import { Download, Printer, RefreshCw } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Cell } from "recharts";
import AppShell from "../../components/AppShell";
import { supabase } from "../../config/supabaseClient";
import { exportCsv, loadReports } from "../../services/reportService";

export default function ReportsAnalytics({ profile }) {
 const today=new Date().toISOString().slice(0,10), first=new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);
 const [filters,setFilters]=useState({from:first,to:today,status:"",veterinarianId:""}),[data,setData]=useState(null),[vets,setVets]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await loadReports(filters));}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();supabase.from("profiles").select("id,full_name,role").eq("role","veterinarian").then(({data})=>setVets(data||[]));},[]);
 const statusData=useMemo(()=>Object.entries(data?.statusCounts||{}).map(([name,value])=>({name,value})),[data]); const sourceData=useMemo(()=>Object.entries(data?.sourceCounts||{}).map(([name,value])=>({name,value})),[data]); const speciesData=useMemo(()=>Object.entries(data?.speciesCounts||{}).map(([name,value])=>({name,value})),[data]);
 const m=data?.metrics||{};
 return <AppShell profile={profile} title="Reports & Analytics"><div className="reports"><div className="head"><div><h2>Clinic Performance Reports</h2><p>Real-time analytics based on Supabase records.</p></div><div><button className="soft" onClick={load}><RefreshCw size={16}/> Refresh</button><button className="soft" onClick={()=>window.print()}><Printer size={16}/> Print</button><button onClick={()=>exportCsv(`pawcruz-appointments-${filters.from}-${filters.to}.csv`,data?.appointments||[])}><Download size={16}/> Export CSV</button></div></div>{error&&<div className="error">{error}</div>}
 <div className="filters"><label>From<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label><label>Veterinarian<select value={filters.veterinarianId} onChange={e=>setFilters({...filters,veterinarianId:e.target.value})}><option value="">All veterinarians</option>{vets.map(v=><option key={v.id} value={v.id}>{v.full_name}</option>)}</select></label><label>Status<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{["Confirmed","Completed","Cancelled"].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={load}>Apply</button></div>
 {loading?<div className="card">Loading analytics...</div>:<><div className="cards">{[["Appointments",m.appointmentTotal],["Online",m.online],["Walk-ins",m.walkIn],["Daily queue",m.queueTotal],["Avg. wait",`${m.averageWait||0} min`],["Avg. consultation",`${m.averageConsultation||0} min`],["Pet registrations",m.petRegistrations],["Medical activity",m.medicalActivity],["Low stock",m.lowStock],["Expiring",m.expiring]].map(([a,b])=><article key={a}><b>{b||0}</b><span>{a}</span></article>)}</div><div className="charts"><section><h3>Appointment Status</h3><ResponsiveContainer width="100%" height={280}><BarChart data={statusData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#4DA8DA"/></BarChart></ResponsiveContainer></section><section><h3>Online vs Walk-In</h3><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={sourceData} dataKey="value" nameKey="name" outerRadius={90} label>{sourceData.map((_,i)=><Cell key={i} fill={["#4DA8DA","#F4B942","#4CAF78"][i%3]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></section><section><h3>Most Common Species</h3><ResponsiveContainer width="100%" height={280}><BarChart data={speciesData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#79C7E3"/></BarChart></ResponsiveContainer></section><section><h3>Inventory Alerts</h3><div className="alertGrid"><div><b>{m.lowStock||0}</b><span>Low/out of stock</span></div><div><b>{m.expiring||0}</b><span>Near expiry/expired</span></div><div><b>{data?.transactions?.length||0}</b><span>Stock transactions</span></div><div><b>{m.users||0}</b><span>Registered users</span></div></div></section></div></>}
 <style>{`.reports{display:grid;gap:18px}.head{display:flex;justify-content:space-between;gap:20px}.head h2{margin:0}.head p{color:#6F7F88}.head>div:last-child{display:flex;gap:8px;align-items:flex-start}button{border:0;background:#4DA8DA;color:#fff;padding:10px 14px;border-radius:10px;display:inline-flex;align-items:center;gap:6px;cursor:pointer}.soft{background:#eaf7fb;color:#237fab}.filters,.charts section,.cards article{background:#fff;border-radius:16px;box-shadow:0 7px 22px rgba(47,117,150,.08)}.filters{display:flex;gap:12px;padding:16px;align-items:end}.filters label{display:grid;gap:5px;flex:1}.filters input,.filters select{padding:10px;border:1px solid #d9e9ef;border-radius:9px}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.cards article{padding:18px}.cards b{font-size:25px;color:#318fbe;display:block}.cards span{color:#6F7F88}.charts{display:grid;grid-template-columns:1fr 1fr;gap:16px}.charts section{padding:18px}.charts h3{margin-top:0}.alertGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.alertGrid div{background:#F2FAFD;padding:20px;border-radius:13px}.alertGrid b{font-size:28px;color:#318fbe;display:block}.alertGrid span{color:#6F7F88}.error{background:#fff0f0;color:#a94444;padding:12px;border-radius:10px}@media(max-width:1000px){.cards{grid-template-columns:repeat(2,1fr)}.charts{grid-template-columns:1fr}}@media(max-width:700px){.head,.filters{flex-direction:column}.head>div:last-child{flex-wrap:wrap}.cards{grid-template-columns:1fr 1fr}}@media print{.sidebar,header,.filters,.head button{display:none!important}main{margin:0}.content{padding:0}}`}</style></div></AppShell>;
}
